#!/bin/bash

if test -f ./remote.env; then
    source ./remote.env
fi 
if test -f ./local.env; then
    source ./local.env
fi
SHA=$(git rev-parse HEAD)
CHANGES=$(git ls-files -m -o --exclude-standard)

if [ "$SHA" != "$last_test_commit" ] || [ ! -z "$CHANGES" ]
then
    echo "testing..."
    export TEST_ID=test-go-bucketfs_$(id -u -nr)_$(date +%F_%H-%M-%S)
    export CLOUDSDK_CORE_PROJECT=$CLOUDSDK_CORE_PROJECT
    export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
    go test . ./gcp
    test -f ./local.env && $((cat local.env | grep -v last_test_commit)> local.new.env)
    echo "last_test_commit=$SHA" >> local.new.env
    test -f ./local.env && rm local.env
    mv local.new.env local.env
else
    echo "no changes since last test"
fi